### ISSUE TITLE
Build fails with Go 1.10

### ISSUE THREAD

**Issue by tbolender** [opennota/findimagedupes#13]
Using the latest Go-Lang version, the build fails with

```
# runtime
go/src/runtime/cgo.go:9:3: //go:cgo_export_static main only allowed in cgo-generated code
```

I am running Ubuntu 16.04 LTS with prebuilt Go.

**Comment by opennota** [comment]
Works for me.
```
opennota@localhost ~ $ go get github.com/opennota/findimagedupes
opennota@localhost ~ $ go version
go version go1.10 linux/amd64
```

It might be a problem with your Go installation.

**Comment by tbolender** [comment]
I just installed Go for trying the project out. I just followed the instructions from https://golang.org/doc/install and called  `go get github.com/opennota/findimagedupes`. Not sure, maybe there was a path problem. I downgraded to 1.9.4 and it worked.

If it works for you, this can be closed.

**Comment by opennota** [comment]
Just tested it in a fresh Ubuntu 16.04 docker container. No errors. Perhaps that was some misconfiguration on your part.
