### ISSUE TITLE
How to delete duplicates?

### ISSUE THREAD

**Issue by rwoodpecker** [opennota/findimagedupes#14]
It would be great if anyone can share how they use this tool to remove duplicate images while keeping the original files intact.

**Comment by opennota** [comment]
You can use the `-p` option to open similar images in a viewer and compare them visually / check their dimensions etc., then delete the ones you do not need (with `feh` the delete is just `Ctrl+D`).

If you need to automate the whole task, I've no answer for you. In general you can't say without looking which images are "original" and which aren't.

**Comment by rwoodpecker** [comment]
Thanks.
